version: '3.8'

services:
  red_tester_log:
    container_name: red_tester_log
    build:
      context: .
      dockerfile: RedAdapterLog/Dockerfile
    networks:
      - caddy
    environment:
      - STORE_PATH=/app/data
      - APIKEY=${APIKEY}
    volumes:
      - red_tester_log_volume:/app/data
    labels:
      caddy: red-tester-log.s1.elias.dev
      caddy.reverse_proxy: "{{upstreams 8080}}"

volumes:
  red_tester_log_volume:


networks:
  caddy:
    external: true
    

